{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "The SpatioTemporal Asset Catalog API - Asset Search",
    "description" : "This is an OpenAPI definition of the SpatioTemporal Asset Catalog API - Asset Search specification.",
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "0.1.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/rhysrevans3/asset-search/1.0.0"
  } ],
  "paths" : {
    "/assets/search" : {
      "get" : {
        "tags" : [ "Asset Search" ],
        "summary" : "searches assets",
        "description" : "Retrieve Assets matching filters.",
        "operationId" : "assetsSearchGET",
        "parameters" : [ {
          "name" : "itemIds",
          "in" : "query",
          "description" : "Array of Item ids to return.",
          "required" : false,
          "style" : "form",
          "explode" : false,
          "schema" : {
            "$ref" : "#/components/schemas/itemIds"
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "The optional limit parameter recommends the number of items that should be present in the response document.\n\nOnly items are counted that are on the first level of the collection in the response document.\nNested objects contained within the explicitly requested items shall not be counted.\n\nMinimum = 1. Maximum = 10000. Default = 10.",
          "required" : false,
          "style" : "form",
          "explode" : false,
          "schema" : {
            "maximum" : 10000,
            "minimum" : 1,
            "type" : "integer",
            "default" : 10
          }
        }, {
          "name" : "datetime",
          "in" : "query",
          "description" : "Either a date-time or an interval, open or closed. Date and time expressions\nadhere to RFC 3339. Open intervals are expressed using double-dots.\n\nExamples:\n\n* A date-time: \"2018-02-12T23:20:50Z\"\n* A closed interval: \"2018-02-12T00:00:00Z/2018-03-18T12:31:12Z\"\n* Open intervals: \"2018-02-12T00:00:00Z/..\" or \"../2018-03-18T12:31:12Z\"\n\nOnly features that have a temporal property that intersects the value of\n`datetime` are selected.\n\nIf a feature has multiple temporal properties, it is the decision of the\nserver whether only a single temporal property is used to determine\nthe extent or all relevant temporal properties.",
          "required" : false,
          "style" : "form",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "content" : {
              "application/geo+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/assetCollection"
                }
              },
              "text/html" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          },
          "default" : {
            "description" : "An error occurred.",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/exception"
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "Asset Search" ],
        "summary" : "searches assets",
        "description" : "Allows for search on assets",
        "operationId" : "assetsSearchPOST",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "allOf" : [ {
                  "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/item-search#/components/schemas/searchBody"
                }, {
                  "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/fragments/fields/openapi.yaml#/components/schemas/searchBody"
                }, {
                  "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/fragments/filter/openapi.yaml#/components/schemas/searchBody"
                }, {
                  "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/fragments/sort/openapi.yaml#/components/schemas/searchBody"
                } ]
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "content" : {
              "application/geo+json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/assetCollection"
                }
              },
              "text/html" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          },
          "default" : {
            "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml#/components/responses/Error"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "assetCollection" : {
        "required" : [ "features", "type" ],
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "enum" : [ "FeatureCollection" ]
          },
          "features" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/asset"
            }
          },
          "links" : {
            "type" : "array",
            "description" : "An array of links. Can be used for pagination, e.g. by providing a link with the `next` relation type.",
            "example" : [ {
              "rel" : "next",
              "href" : "http://api.cool-sat.com/search?next=ANsXtp9mrqN0yrKWhf-y2PUpHRLQb1GT-mtxNcXou8TwkXhi1Jbk"
            } ],
            "items" : {
              "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml#/components/schemas/link"
            }
          }
        },
        "description" : "A GeoJSON FeatureCollection augmented with foreign members that contain values relevant to a STAC asset"
      },
      "asset" : {
        "required" : [ "bbox", "geometry", "id", "links", "properties", "stac_version", "type" ],
        "type" : "object",
        "properties" : {
          "stac_version" : {
            "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml#/components/schemas/stac_version"
          },
          "stac_extensions" : {
            "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml#/components/schemas/stac_extensions"
          },
          "id" : {
            "type" : "string"
          },
          "links" : {
            "$ref" : "https://api.stacspec.org/v1.0.0-beta.5/core/openapi.yaml#/components/schemas/links"
          }
        },
        "description" : "A GeoJSON Feature augmented with foreign members that contain values relevant to a STAC asset",
        "example" : {
          "stac_version" : "1.0.0",
          "stac_extensions" : [ "https://stac-extensions.github.io/eo/v1.0.0/schema.json", "https://stac-extensions.github.io/view/v1.0.0/schema.json", "https://example.com/cs-extension/1.0/schema.json" ],
          "type" : "Feature",
          "id" : "CS3-20160503_132131_05",
          "properties" : {
            "datetime" : "2016-05-03T13:22:30.040Z",
            "title" : "A CS3 item",
            "license" : "PDDL-1.0",
            "providers" : [ {
              "name" : "CoolSat",
              "roles" : [ "producer", "licensor" ],
              "url" : "https://cool-sat.com/"
            } ],
            "view:sun_azimuth" : 168.7,
            "eo:cloud_cover" : 0.12,
            "view:off_nadir" : 1.4,
            "platform" : "coolsat2",
            "instruments" : [ "cool_sensor_v1" ],
            "eo:bands" : [ ],
            "view:sun_elevation" : 33.4,
            "eo:gsd" : 0.512
          },
          "collection" : "CS3",
          "links" : [ {
            "rel" : "self",
            "href" : "http://cool-sat.com/collections/CS3/items/20160503_132130_04"
          }, {
            "rel" : "root",
            "href" : "http://cool-sat.com/collections"
          }, {
            "rel" : "parent",
            "href" : "http://cool-sat.com/collections/CS3"
          }, {
            "rel" : "collection",
            "href" : "http://cool-sat.com/collections/CS3"
          } ]
        }
      },
      "itemIds" : {
        "type" : "array",
        "description" : "Array of Item ids to return.",
        "items" : {
          "type" : "string"
        }
      },
      "exception" : {
        "required" : [ "code" ],
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          }
        },
        "description" : "Information about the exception: an error code plus an optional description."
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/exception"
            }
          }
        }
      }
    },
    "parameters" : {
      "itemIds" : {
        "name" : "itemIds",
        "in" : "query",
        "description" : "Array of Item ids to return.",
        "required" : false,
        "style" : "form",
        "explode" : false,
        "schema" : {
          "$ref" : "#/components/schemas/itemIds"
        }
      }
    }
  }
}